### ISSUE TITLE
MFR / Forestry Farms integration for nether crops

### ISSUE THREAD

**Issue by Neodark7** [ganymedes01/Gany-s-Nether#14]
Can you make that ? :3

**Comment by Neodark7** [comment]
if no, how many time do they need to grow ? :P

**Comment by ganymedes01** [comment]
Made it for MFR.
I'll look into forestry, if it's not too convoluted I'll add for it too :3

**Comment by Neodark7** [comment]
you've just added it for MFR ? :o 
however works perfectly with EnderIO farm station ( at least for the nether quarz bush )

**Comment by ganymedes01** [comment]
That's good to know :3
But I doubt the farm station will harvest wither skulls from or ghast tears. But MFR will :D

**Comment by Neodark7** [comment]
So fruit picker for the ghast tears and wither skulls and harvester for the rest ?

**Comment by ganymedes01** [comment]
Harvester for everything :3

**Comment by Neodark7** [comment]
new update soon or do i need to build it myself ? :3
