### ISSUE TITLE
One suggestion, One bug, One question

### ISSUE THREAD

**Issue by Neodark7** [ganymedes01/Gany-s-Nether#15]
bug : the wither seed drop vanilla wheat seed when harvested
suggestion : for the MFR integration can you add the wither and quartz seeds to the bioreactor ?
question : ETA for the MFR integration update ? :3

**Comment by ganymedes01** [comment]
-Not sure why the wither shrub is dropping the vanilla seed O_O How did you harvest it? bare hands?
-Yes I can :3
-Not sure yet, but probably not long :)

**Comment by Neodark7** [comment]
yup :v http://imgur.com/a/3GxKi

**Comment by ganymedes01** [comment]
Weird, I think I fixed it :3

**Comment by Neodark7** [comment]
hey :) ETA for the update ? :D

**Comment by ganymedes01** [comment]
Today ;D

**Comment by Neodark7** [comment]
omg HYPE :D
