### ISSUE TITLE
Sceptre of Concealment derpyness

### ISSUE THREAD

**Issue by ZeekDaGeek** [ganymedes01/Gany-s-Nether#16]
The Sceptre of Concealment is apparently made out of the most flimsy material ever.

First when crafted it appears to have 0 durability so it looks like it's about to break, but it doesn't thankfully.
http://zeekdageek.tv/ss/ANFKh.png

I think it's because it's crafted with 128 metadata instead of 127. 0 would counts for a use so it still has 128 real durability.

Right clicking with the Sceptre destroys it.
Left clicking with no egg destroys it.
Left clicking on a player destroys it.

I'm running out of nether stars. D:

**Comment by ganymedes01** [comment]
You need to fix it in an anvil after you craft it :)

**Comment by ZeekDaGeek** [comment]
Okay, different problem then, it works after you craft it and goes into negative durability or something until you do one of the actions above.
