### ISSUE TITLE
New MFR integration error

### ISSUE THREAD

**Issue by Staegrin** [ganymedes01/Gany-s-Nether#18]
First I want to thank you for making the plants MFR compatible.
Sadly,
![2015-02-22_17 24 59](https://cloud.githubusercontent.com/assets/8494635/6319301/c8f85464-bab7-11e4-9af3-8b54a3dd40e7.png)
 it seems the planter overwrites the already planted weeping pods with new ones as soon as the weeping pods that are already planted start to mature.

As you can see the planter only uses the 4 sides of the 2nd obsidian above it to plant the ghast tears.
As soon as the resulting weeping pods start to mature they are replaced before maturing completely. The number of ghast tears in the planter goes down while the harvester doesn't harvest any because none reach maturity.
![2015-02-22_17 28 29](https://cloud.githubusercontent.com/assets/8494635/6319309/436f9e82-bab8-11e4-8b4b-0748712261c6.png)
Started with a stack of 64. I see weeping pods being replaced without any being harvested by the harvester

Have tested by turning the planter off and the weeping pods get harvested by the harvester correctly. Though I did need to put the harvester on the same level as the mature weeping pods.

**Comment by ganymedes01** [comment]
That's strange, I remember testing this shortly before release and it was working.
Perhaps I was using an outdated version of MFR... I'll try again in a bit.
Thanks for the detailed report :)
