### ISSUE TITLE
Localize version checker

### ISSUE THREAD

**Issue by Adaptivity** [ganymedes01/Gany-s-Nether#19]
https://github.com/ganymedes01/Gany-s-Nether/blob/37ff9f7e60f8715f4ae78aead46188fedd7f9f9f/src/main/java/ganymedes01/ganysnether/core/utils/VersionHelper.java#L101-L103 also do it for all your mods.

**Comment by ganymedes01** [comment]
Will do. Can't believe I forgot to localise those >_>

**Comment by ganymedes01** [comment]
Realised a problem...
You don't happen to know how to make translated text have colours do you?

**Comment by Adaptivity** [comment]
You can try to do something like this: https://github.com/Prototik/BuildCraft/commit/93806cecca4274610adbcb2e0c836f4ca15a1a60

**Comment by ganymedes01** [comment]
Took me a while to get around to it, but it's finally done!
