### ISSUE TITLE
[Issue]: Scepter Of Concealment Recipe Bug

### ISSUE THREAD

**Issue by Lanse505** [ganymedes01/Gany-s-Nether#21]
Seems the Scepter of Concealment recipe doesn't work according to my group of testers, They try the recipe and it simply doesnt want to turn the Depleted+Cap to a fully repaired.

**Comment by Lanse505** [comment]
Btw Hiya Gany :3

**Comment by ganymedes01** [comment]
Tell them to try it in an anvil.
I changed it a while back but didn't update the wiki :3

**Comment by ganymedes01** [comment]
I'm changing that though.
I don't like that mechanic anymore.
Newly crafted sceptres will have full durability as of the next update :)
