### ISSUE TITLE
Improve mcmod.info

### ISSUE THREAD

**Issue by Adaptivity** [ganymedes01/Gany-s-Nether#22]
Yes, I can make a PR but I'm not sure if it will work.
See: https://github.com/SlimeKnights/TinkersConstruct/blob/master/resources/mcmod.info#L6 modversion should be more dynamic if you change it to *${version}*. You should also add *"mcversion": "${MCversion}",* to mcmod.info. And don't forget to apply this to all your mods.
Also, you should add pack.mcmeta to all your mods :smile: it's very minor thing but this prevent FML from spamming logs about missing pack.mcmeta.

**Comment by ganymedes01** [comment]
Everytime I tried using that it didn't work. And with gradle, the least I can fiddle the best lol
Also, the pack,mcmeta files were added by you a few days ago XD

**Comment by Adaptivity** [comment]
I'm added the pack.mcmeta but not for all your mods. You should add to the rest of them.

**Comment by Adaptivity** [comment]
Possible solution: Create build.properties(example: https://github.com/SlimeKnights/TinkersConstruct/blob/master/build.properties) and then add *"mcversion": "${MCversion}"* and change static *"version": xxx* to dynamic *"${version}"*

**Comment by ganymedes01** [comment]
Added the pack.mcmeta to all of my mods.
I'll try doing the build.properties thing you mentioned. But I'm a bit scared of fiddling with gradle since I don't really know how it works and a single misplaced comma can blow everything up XD
