### ISSUE TITLE
Server crashloop if configs are changed

### ISSUE THREAD

**Issue by Saereth** [ganymedes01/Gany-s-Nether#33]
Seems like a strange interaction with Thaumcraft, but reporting to both mod developers.

If I change nearly any setting in the config (although in this particular instance I set withershrubs to false, no other changes were made) The server hard crashes every boot until I change it back.

forge 1448, latest thaumcraft 4.2.3.5,  Gany'sNether 1.8.1

Here is the entire crashlog

http://pastebin.com/m94GqDkS

**Comment by ganymedes01** [comment]
It's my fault, you need not disturb Azanor with this

**Comment by ganymedes01** [comment]
As to why it's happening,
it seems to be relates to a few configs that I didn't imenente properly (as in, they are only "partially" disabled).
So would you mind telling me which configs you toggled in the file? I've identified te problem with the wither shurb config but I don't see any other that would be causing an issue

**Comment by Saereth** [comment]
The only config I changed was setting the     B:"wither shrub"=true to     B:"wither shrub"=false

**Comment by ganymedes01** [comment]
Okay :)
Well there's a workaround for it:
Either leave the config on, or turn off the integration with Thaumcraft.

I'm working on a fix.
