### ISSUE TITLE
Sceptre of Concealment and Iron Golems

### ISSUE THREAD

**Issue by Thistlebalm** [ganymedes01/Gany-s-Nether#34]
I'm playing on a server with Gany's Nether-1.8.0, using the Resonant Rise Mainline base pack. If the full modlist is needed I'll try to get it.

Iron Golem(vanilla minecraft) was made using iron blocks and a pumpkin. Left-clicking on the golem with the Sceptre of Concealment deals 1 damage and uses a chicken egg but drops no iron golem egg and the iron golem stays alive. 
EDIT: It appears that the eggs aren't actually used, it 'takes' them but if I move the stack I get them back.

The Sceptre of Concealment also doesn't seem to work on Thaumcrafts tainted mobs, but I don't think it takes away the egg.

**Comment by ganymedes01** [comment]
It won't work on every mob, only the vanilla ones.
I fixed the de-sync caused by taking (or not) the eggs though :)

**Comment by Thistlebalm** [comment]
The Iron Golem from vanilla isn't working, but it is in single player so it's probably something on the server that's messing with it. Thanks though :)

I also wasn't sure if you were doing modded mob support with the eggs or not since the sceptre works on Ender Zoo mobs too, though I guess they could have coded it nicely enough that it has compatibility innately.

**Comment by ganymedes01** [comment]
Do you use NEI ?
By default the Iron Golem doesn't have a spawn egg, but NEI adds one. So if it's not working it might be because you don't have that mod.

**Comment by ganymedes01** [comment]
There are two ways of registering a mob in Minecraft. The vanilla way (which has a hard limit of 128 and can cause ID conflicts) and Forge's way (which is limitless and has no id conflicts).
Mods that register their mobs using vanilla's way will be supported by the sceptre (since from the sceptres point of view, that mob is vanilla). Mobs added the forge way probably won't, since there's no way to guarantee if those mobs have a spawn egg and if they do, what item is it.

**Comment by Thistlebalm** [comment]
Yup definitely using NEI, maybe it's not on the server though. It's not my server or anyone I know well enough to get much information out of. Actually I just thought of this, we are using INpure Core. I know it hides all the spawn eggs by default, I wouldn't think that affects it though.

Thanks for the insights, I appreciate you explaining the way things work to me. By the way I think your mods are great and I spread the word on the server and /r/feedthebeast about them :)
