### ISSUE TITLE
Hardcoded stuff spotted!

### ISSUE THREAD

**Issue by Adaptivity** [ganymedes01/Gany-s-Nether#36]
[Extended Spawner](https://github.com/ganymedes01/Gany-s-Nether/blob/efd49528f84cc94afd8fb9760a2de8a77e9f33ed/src/main/java/ganymedes01/ganysnether/tileentities/TileEntityExtendedSpawner.java#L72-L88)
[Boo.](https://github.com/ganymedes01/Gany-s-Nether/blob/efd49528f84cc94afd8fb9760a2de8a77e9f33ed/src/main/java/ganymedes01/ganysnether/items/LivingSoul.java#L37)
[Command message](https://github.com/ganymedes01/Gany-s-Nether/blob/efd49528f84cc94afd8fb9760a2de8a77e9f33ed/src/main/java/ganymedes01/ganysnether/command/GanysNetherCommand.java#L69) new ChatComponentTranslation here.
@ganymedes01 please fix.

**Comment by ganymedes01** [comment]
Will fix! Thanks for letting me know :3

**Comment by Adaptivity** [comment]
new ChatComponentText doesn't working server side as I know. It will always show English localization. Change this to ChatComponentTranslation.

**Comment by ganymedes01** [comment]
Oh I didn't know that, sorry.
Fixing it now.

**Comment by ganymedes01** [comment]
Done
