### ISSUE TITLE
Sugestion: MagmaticCentrifuge (MC 1.7.10)

### ISSUE THREAD

**Issue by Blue64** [ganymedes01/Gany-s-Nether#38]
I was tinkering around with my ```%appdata%\.minecraft\config\GanysMods\Recipes\MagmaticCentrifuge.xml``` today, and fully customized it, but I found out the hard way (hard crash, killed launcher process) that it doesn't support multiple ```oreDictionary``` items in 1 slot, example:
```
    <input1>minecraft:diamond_horse_armor 1 0</input1>
    <input2>"gemDiamond" 3</input2>
    <output1>minecraft:diamond 9 0</output1>
```
I'd provide a full example, but, well, I'm about to post the BUG part separately, as it's only partially related, you'll see there.
I'll be providing the crash log links in the BUG issue (which I'll reference to here shortly).

**Comment by ganymedes01** [comment]
Should be working as of 1.8.2
