### ISSUE TITLE
Bug: MagmaticCentrifuge (MC 1.7.10)

### ISSUE THREAD

**Issue by Blue64** [ganymedes01/Gany-s-Nether#39]
I was tinkering around with my config files (#38 contains a portion of some of the tinkering, but basically I'm trying to completely customize my personal ModPack), and as i was tinkering, I randomly decided to to a test launch (I needed my specs for [a recommendation for Forge](https://github.com/MinecraftForge/MinecraftForge/issues/2304) to delete old useless Forge files, but I regularly clear out my ```.log``` files), I encountered a Hard Crash for the Forge Launcher caused by my ```MagmaticCentrifuge.xml``` (which promptly deleted ALL of it's contents: ```File Size: 0 bytes```) caused by trying to have ```<Input2>"gemDiamond" 3</input2>``` (```3``` of any of the ```gemDiamond``` ```oreDictionary``` ```item``` in the ```2nd input slot```) (also referenced in issue 38).

Also, I'm not sure how, or where it came from, but apparently it thinks I added a fluid to the ```MagmaticCentrifuge.xml``` recipe list, which I didn't, I only shortened the Dye recipes to 50, and lengthened a few others, but I added no fluids.

* Edit: still uploading the Error Logs to my GitHub ([Misc section](https://github.com/Blue64/Misc))

**Comment by Blue64** [comment]
Crash Log 1:
* [Section 1](https://github.com/Blue64/Misc/blob/master/Gany's%20Nether%20Crash%201.log#L5131-L5196)
* [Section 2](https://github.com/Blue64/Misc/blob/master/Gany's%20Nether%20Crash%201.log#L5131-L5196)
* [Crash Report](https://github.com/Blue64/Misc/blob/master/Gany's%20Nether%20Crash%201.log#L5999-L6393)

**Comment by Blue64** [comment]
Crash Log 2 is basically caused by the recipe file located at ```%appdata%\.minecraft\config\GanysMods\Recipes\MagmaticCentrifuge.xml``` to be empty (```File Size: 0 bytes```). (i accidentially deleted my log of the crash lol sorry)

**Comment by Blue64** [comment]
I also just noticed ```GanysEnd``` depends on ```EnderStorage```, this has never popped up at any point during my use of the mod, is that a soft dependency?

**Comment by ganymedes01** [comment]
Thank you for your thorough report. I'll have a look into it as soon as possible.

Gany's End never depended on Ender Storage. Try to load Gany's End without Ender Storage and you'll see it will work :)

**Comment by Blue64** [comment]
I've never used Ender Storage lol that's why I thought it was weird that it says in the Log that it depended on Ender Storage

**Comment by ganymedes01** [comment]
Should be working as of 1.8.2
