### ISSUE TITLE
More Hoes need to Till Netherrack

### ISSUE THREAD

**Issue by Fortist** [ganymedes01/Gany-s-Nether#42]
Add config list to add hoes, out of 20 some hoes only diamond is usable. This is bullshit.

**Comment by Blue64** [comment]
I too have lots of Hoes added to my game (M-Ore, Magical Crops, etc) and I've noticed that only the Vanilla Hoes work. the [Duke605's GreenThumb](http://duke605.github.io/micro-mods/green-thumb/) (as opposed to [DoubleDoorDevelopment's](http://doubledoordev.net/?p=modlist&mod=GreenThumb)) Torch of Growth doesn't recognize it either, not sure if it even speeds up the TickRate for the crops involved.
